[rocprofiler-sdk][CI] format config.yaml

diff --git a/.github/workflows/rocprofiler-sdk-formatting.yml b/.github/workflows/rocprofiler-sdk-formatting.yml
--- a/.github/workflows/rocprofiler-sdk-formatting.yml
+++ b/.github/workflows/rocprofiler-sdk-formatting.yml
@@ -1,6 +1,9 @@
 
 name: rocprofiler-sdk Formatting
 
+permissions:
+  contents: read
+
 on:
   workflow_dispatch:
   pull_request:
@@ -173,5 +176,37 @@ jobs:
           echo -e "\nError! Source code missing new line at end of file...\n"
           echo -e "\nFiles:\n"
           cat ${OUTFILE}
+          exit 1
+        fi
+
+  config_yaml:
+    runs-on: ubuntu-22.04
+
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        sparse-checkout: projects/rocprofiler-sdk
+
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.10'
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        python -m pip install ruamel.yaml
+
+    - name: Ensure config.yaml is formatted
+      working-directory: projects/rocprofiler-sdk
+      run: |
+        python source/scripts/format-deps.py --counter-config
+        if [ $(git diff -- source/share/rocprofiler-sdk/config.yaml | wc -l) -ne 0 ]; then
+          echo ""
+          echo "::error::YAML file is not properly formatted. Run the following command to fix:"
+          echo ""
+          echo "  cd projects/rocprofiler-sdk && python source/scripts/format-deps.py --counter-config"
+          echo ""
+          git diff -- source/share/rocprofiler-sdk/config.yaml
           exit 1
         fi
